package uk.org.nbn.nbnv.api.nxf;

public enum NXFHeading {
    RECORDKEY, TAXONVERSIONKEY, SITEKEY, SITENAME, NORTH, EAST, NORTHINGS, 
    EASTINGS, LAT, LONG, LATITUDE, LONGITUDE, SRS, DATE, RECORDER, DETERMINER, 
    ZEROABUNDANCE, SURVEYKEY, SAMPLEKEY, DYNAMICPROPERTIES, PROJECTION, SENSITIVE, 
    GRIDREFERENCE, PRECISION, DATETYPE, STARTDATE, ENDDATE, FEATUREKEY;
}
