USE [master]
GO

/****** Object:  Database [NBNWarehouse]    Script Date: 09/09/2013 12:14:01 ******/
CREATE DATABASE [NBNWarehouse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NBNWarehouse', FILENAME = N'G:\Databases\NBNWarehouse.mdf' , SIZE = 130698240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NBNWarehouse_log', FILENAME = N'G:\TransactionLogs\NBNWarehouse_log.ldf' , SIZE = 45631808KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NBNWarehouse] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NBNWarehouse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NBNWarehouse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NBNWarehouse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NBNWarehouse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NBNWarehouse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NBNWarehouse] SET ARITHABORT OFF 
GO

ALTER DATABASE [NBNWarehouse] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NBNWarehouse] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NBNWarehouse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NBNWarehouse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NBNWarehouse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NBNWarehouse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NBNWarehouse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NBNWarehouse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NBNWarehouse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NBNWarehouse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NBNWarehouse] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NBNWarehouse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NBNWarehouse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NBNWarehouse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NBNWarehouse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NBNWarehouse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NBNWarehouse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NBNWarehouse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NBNWarehouse] SET RECOVERY FULL 
GO

ALTER DATABASE [NBNWarehouse] SET  MULTI_USER 
GO

ALTER DATABASE [NBNWarehouse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NBNWarehouse] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NBNWarehouse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NBNWarehouse] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

USE [NBNWarehouse]
GO

/****** Object:  User [NBNAPI]    Script Date: 09/09/2013 12:14:01 ******/
CREATE USER [NBNAPI] FOR LOGIN [NBNAPI] WITH DEFAULT_SCHEMA=[dbo]
GO

/****** Object:  User [NBNGIS]    Script Date: 09/09/2013 12:14:02 ******/
CREATE USER [NBNGIS] FOR LOGIN [NBNGIS] WITH DEFAULT_SCHEMA=[dbo]
GO

GRANT CONNECT TO [NBNAPI] AS [dbo]
GO

GRANT EXECUTE TO [NBNAPI] AS [dbo]
GO

GRANT SELECT TO [NBNAPI] AS [dbo]
GO

GRANT CONNECT TO [NBNGIS] AS [dbo]
GO

GRANT EXECUTE TO [NBNGIS] AS [dbo]
GO

GRANT SELECT TO [NBNGIS] AS [dbo]
GO

ALTER DATABASE [NBNWarehouse] SET  READ_WRITE 
GO


